### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by creage** [no23reason/jest-trx-results-processor#110]
Trying to run `jest` from command line having reporter set to `jest-trx-results-processor`

``jest --reporters=jest-trx-results-processor``

ends up with error

``
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:113:11)
    at Object.resolve (path.js:139:9)
    at TrxReporter.onRunComplete (C:\Git\client\node_modules\jest-trx-results-processor\dist\index.js:20:67)
``

**Comment by no23reason** [comment]
Thank you for the report, I'll try have a look at it when I got the time (this weekend).
