### ISSUE TITLE
Dynamic Filename for TRX using environment variables?

### ISSUE THREAD

**Issue by JakeStevenson** [no23reason/jest-trx-results-processor#154]
I am using a jest runner that will execute a suite of tests multiple times in parallel.  I'd like to be able to have the results-processor output a different trx file for each of these executions, possibly based off an environment variable.  

Would it be possible to allow it's output filename to be overwritten as such?

`
export JEST_TRX_FILE="$BROWSER"-results.trx
`

**Comment by no23reason** [comment]
Hi, I guess this could be done using [`jest.config.js`](https://jestjs.io/docs/en/configuration) (since it is a js file, you can generate the outputFile value however you like). Something along the lines of

```js
module.exports = {
  reporters: [
     "default",
     [
       "jest-trx-results-processor",
       {
         outputFile: `./${process.env.BROWSER}-results.trx`
       }
     ]
  ]
  // rest of your jest config
}
```

**Comment by JakeStevenson** [comment]
That works very well, thank you!
