### ISSUE TITLE
"RangeError: Invalid time value" is thrown when the test run contains test.todo()

### ISSUE THREAD

**Issue by MasonBergstrom** [no23reason/jest-trx-results-processor#197]
Getting "RangeError: Invalid time value" exception whenever a test makes use of test.todo(). 

This appears to be related to #22 which was fixed as part of #23. 
Looks like that fix will just need expanded slightly.

**Comment by MasonBergstrom** [comment]
Just realized I'm further out of date than I thought, will update to newest version and test again.

**Comment by no23reason** [comment]
Hi, thank you for the report, I'll look into it when I have the time :)

**Comment by no23reason** [comment]
@MasonBergstrom thank you again for your well researched bug report, it was indeed related to the issue you mentioned. The fixed version should be released in a few minutes.
