### ISSUE TITLE
codeBase should provide the actual fill path of test suite file

### ISSUE THREAD

**Issue by deepakkamboj** [no23reason/jest-trx-results-processor#226]
codeBase should provide the actual fill path of test suite file. Currently, codeBase and Name are providing same string.

codeBase should provide name of actual file name of test suite containing the test case.

this can be provided using below code:

	   // Build variables for suite name
    const filepath = path.relative('./', testRunResult.testFilePath);
    const filename = path.basename(filepath);

**Comment by no23reason** [comment]
Hi, thank you for the issue. If you have the time a PR would be very welcome.

**Comment by deepakkamboj** [comment]
I am trying to push changes, I am getting below error:

D:\jest-trx-results-processor>git push --set-upstream origin AddFilePathToTrx
remote: Permission to no23reason/jest-trx-results-processor.git denied to deepakkamboj.
fatal: unable to access 'https://github.com/no23reason/jest-trx-results-processor/': The requested URL returned error: 403

I have pushed changes to form branch:
https://github.com/deepakkamboj/jest-trx-results-processor

Please  provide me permission for contributing to the code

**Comment by no23reason** [comment]
Sorry, I did not notice this comment, but I see you have already opened a PR, thank you for that :)

**Comment by deepakkamboj** [comment]
Hi

I have created a new pull request will all the changes suggested by you:
https://github.com/deepakkamboj/jest-trx-results-processor/pull/5  

Please commit this PR in your repository:
https://github.com/no23reason/jest-trx-results-processor 

Please create a new NPM package from the above pull request.

**Comment by deepakkamboj** [comment]
Please review the below Pull Request:

https://github.com/no23reason/jest-trx-results-processor/pull/269

**Comment by no23reason** [comment]
Merged, thank you for the contribution!

**Comment by no23reason** [comment]
Fixed in #269
