### ISSUE TITLE
"Skipped" is not a valid outcome value and does not match karma-trx-reporter's outcome

### ISSUE THREAD

**Issue by hmafzal** [no23reason/jest-trx-results-processor#24]
Currently, this results processor outputs a "Skipped" outcome for any tests which are marked to be skipped. However, this does not match what [karma-trx-reporter outputs](https://github.com/hatchteam/karma-trx-reporter/blob/master/index.js#L163) or what [Visual Studio's api lists](https://www.visualstudio.com/en-us/docs/integrate/api/test/results) (see outcome property of Add test results to a test run section). Both list the outcome should be NotExecuted for skipped tests.

Can we switch the outcome of skipped tests to be NotExecuted instead of Skipped to align with the above? I can submit a PR for this if it sounds good.

**Comment by no23reason** [comment]
Hi, sorry for the late response. I think the change you propose is good, if you opened a PR for this, it would be appreciated :)

**Comment by no23reason** [comment]
Fixed, released as [0.0.7](https://github.com/no23reason/jest-trx-results-processor/releases/tag/v0.0.7).

**Comment by hmafzal** [comment]
@no23reason no worries, thanks for fixing this! I missed the last comment saying the change was good.
