### ISSUE TITLE
Any chance I might specify the package name?

### ISSUE THREAD

**Issue by szalapski** [no23reason/jest-trx-results-processor#29]
It is working well for me.

My results are coming through as package "(root)".  Could there be a way, perhaps in the builder({}) object, where I can specify a package name?  I might want to put "(Javascript tests)" or something similar there.  Alternatively, you could just hard code "Jest tests", perhaps.

**Comment by no23reason** [comment]
Hi, I'm glad it works for you. As per your problem, I don't really set this string from my code. Could you please  provide an example TRX file so that we can diagnose where the string you mentioned comes from?

**Comment by no23reason** [comment]
Closing as inactive
