### ISSUE TITLE
require is not a function

### ISSUE THREAD

**Issue by jessemlay** [no23reason/jest-trx-results-processor#30]
I receive a require not defined

TypeError: require(...) is not a function
    at processResults (C:\Users\jesse.lay\Desktop\new app\versaweb_2019_edition\node_modules\jest-cli\build\runJest.js:126:55)
    at C:\Users\jesse.lay\Desktop\new app\versaweb_2019_edition\node_modules\jest-cli\build\runJest.js:211:12
    at Generator.next (<anonymous>)
    at step (C:\Users\jesse.lay\Desktop\new app\versaweb_2019_edition\node_modules\jest-cli\build\runJest.js:1:260)
    at C:\Users\jesse.lay\Desktop\new app\versaweb_2019_edition\node_modules\jest-cli\build\runJest.js:1:420
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

  "scripts": {
      "start": "node scripts/start.js",
      "build": "node scripts/build.js",
      "test": "node scripts/test.js --env=jsdom --json",
      "test:ci": "jest --coverage"
   },
 "jest": {
      "testResultsProcessor": "./scripts/jestTrxProcessor",
      "collectCoverageFrom": [
         "src/**/*.{js,jsx,mjs}"
      ],
      "setupFiles": [
         "<rootDir>/config/polyfills.js"
      ],
      "testMatch": [
         "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
         "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
      ],
      "testEnvironment": "node",
      "testURL": "http://localhost",
      "transform": {
         "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
         "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
         "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
      },
      "transformIgnorePatterns": [
         "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
      ],
      "moduleNameMapper": {
         "^react-native$": "react-native-web"
      },
      "moduleFileExtensions": [
         "web.js",
         "js",
         "json",
         "web.jsx",
         "jsx",
         "node",
         "mjs"
      ]

**Comment by no23reason** [comment]
Thank you for opening the issue. At first glance, I don't really know what could be causing the error. Does the problem go away when you remove the line with `"testResultsProcessor": "./scripts/jestTrxProcessor",`? I'm just trying to be sure your problem is related to this library.

**Comment by jessemlay** [comment]
Oddly enough i came in this morning and everything works great! Sorry about the false alarm

**Comment by no23reason** [comment]
@jessemlay No problem, I'm glad it works now :)
