### ISSUE TITLE
Switching to reporters API

### ISSUE THREAD

**Issue by kachkaev** [no23reason/jest-trx-results-processor#32]
Jest no longer supports `testResultsProcessor` (see https://github.com/jest-community/jest-junit/issues/56). Looks like the new configuration syntax should look something like this:

```json
{
  "jest": {
    "reporters": ["default", "jest-trx-results-processor"]
  }
}
```

or 

```json
{
  "jest": {
    "reporters": [
      "default",
      ["jest-trx-results-processor", { "outputFile": "./myFile.trx" }]
    ]
  }
}
```

I've tried this in Jest 23.6 but it did not produce any outcome, as if `jest-trx-results-processor` was not used at all. What can be missing?

**Comment by kachkaev** [comment]
Processor API has changed. JUnit example: https://github.com/jest-community/jest-junit/blob/master/index.js

This quick tweak in published `dist/index.js` did the trick:

```js
"use strict";
var fs_1 = require("fs");
var trx_generator_1 = require("./trx-generator");
var processor = function(globalConfig, options) {
  if (options === void 0) {
    options = {
      outputFile: "test-results.trx",
    };
  }

  this._globalConfig = globalConfig;
  this._options = options;

  this.onRunComplete = (contexts, results) => {
    process.stdout.write("Generating TRX file...");
    var trx = trx_generator_1.generateTrx(results);
    fs_1.writeFileSync(options.outputFile, trx, { encoding: "utf8" });
    process.stdout.write("DONE\n");
    process.stdout.write("TRX file output to '" + options.outputFile + "'\n");
    // Return the input testRunResult to allow for chaining other result processors
    // return testRunResult;
  };
};
module.exports = processor;
```

**Comment by no23reason** [comment]
@kachkaev Sorry for not responding, I was on vacation. I'll investigate this over the weekend, ok? Thanks for pointing the bug out :)

**Comment by no23reason** [comment]
@kachkaev I looked a bit into the issue and there is no sign that `testResultsProcessor` is to be removed from jest https://jestjs.io/docs/en/configuration.html#testresultsprocessor-string
The issue you link to does not provide any source for the claim the `testResultsProcessor` is going to be removed and also there is no real migration strategy :-/

**Comment by stonemonkey** [comment]
testResultsProcessor is not supported by CRA. It would be helpful to have a custom reporter instead as @kachkaev suggested.

**Comment by no23reason** [comment]
Unfortunately, I may not have the capacity to implement this :-/ PR are very welcome, I'll try to look into it, but I cannot make any promises (I don't use this package anymore myself, so it's not really on the top of my priority list).
