### ISSUE TITLE
Getting error Missing attribute value for attribute runUser of element TestRun in Docker container

### ISSUE THREAD

**Issue by jamesBennett** [no23reason/jest-trx-results-processor#82]
When run locally it works fine. The .trx file is created where I expect it to.
The same tests run in docker causes the error
Missing attribute value for attribute runUser of element TestRun

**Comment by no23reason** [comment]
So the locally created trx file is fine?

**Comment by no23reason** [comment]
It could be caused by the docker image you use does not set any of the values we check when determining the user, see https://github.com/no23reason/jest-trx-results-processor/blob/master/src/utils.ts#L59

**Comment by jamesBennett** [comment]
> It could be caused by the docker image you use does not set any of the values we check when determining the user, see https://github.com/no23reason/jest-trx-results-processor/blob/master/src/utils.ts#L59

Yup this is the issue. I found that bit going through my error logs.
Shouldn't it set the user to 'anonymous' or something if a user name isn't found instead of throwing an error?

**Comment by no23reason** [comment]
We can make that change, sure :) PR would be welcome, otherwise I'll look into it when I have the time
