### ISSUE TITLE
Only output when run on CI

### ISSUE THREAD

**Issue by jesperorb-caspeco** [no23reason/jest-trx-results-processor#95]
**Configuration**

I am using your package tor publish my test results to *Azure Devops*. The way I am using it is the following:

* Reference a processor file in `package.json`, under `jest`-configuration
```
"testResultsProcessor": "<rootDir>/jestTrxProcessor.js"
```
* The `jestTrxProcessor.js`-file looks like the following:
```js
var builder = require('jest-trx-results-processor');
var processor = builder({
    outputFile: 'jestTestResults.trx' 
});
module.exports = processor;
```

**Problem**

I want to skip processing the trx when running locally. Now it is being run on every test. I instead want it to run only when `Azure Devops` runs the tests. How is the best way to do this? When reading the readme it states that this is not the prefered way to run your package and will be removed. Does the newer configuration method support running only on CI? Or is that a configuration to set in jest itself?

**Comment by no23reason** [comment]
Hi, one of the ways to accomplish this is to have separate [jest config file](https://jestjs.io/docs/en/configuration) for dev and for ci. That way you, can set the `testResultsProcessor`/`reporter` only in the ci config. You can tell jest which config to use using the [`--config`](https://jestjs.io/docs/en/cli#config-path) flag:

**Comment by jesperorb-caspeco** [comment]
Thank you! I will try to set up different config files, sound like a something that would be useful in the future.

**Comment by no23reason** [comment]
I'm glad I could help :)
